name: Run NeoLoad from GitHub Actions

on:
  workflow_dispatch:  # This enables the manual trigger button in GitHub UI
  
jobs:
  run-neoload:
    runs-on: self-hosted  # Use the latest Windows runner 
    
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: sweisfeldt/NeoLoadActions
          ref: master  # Specify the master branch
          path: NeoLoadActions
          fetch-depth: 1
    - name: Run NeoLoad commands in cmd
        run: |
          neoload login 9e735913961c346857f02a7b923a9b485f6e739c25458206
          neoload workspaces use CAT_Financial
          neoload run SampleTest
        shell: cmd
