name: Run NeoLoad Test

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  run-neoload:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NeoLoad CLI (if needed)
        run: |
          echo "Assuming NeoLoad CLI is already installed. If not, add install step here."

      - name: Run NeoLoad commands
        run: |
          neoload login 9e735913961c346857f02a7b923a9b485f6e739c25458206
          neoload workspaces use CAT_Financial
          neoload run SampleTest
        shell: cmd
