name: Run NeoLoadCMD.exe on Windows

on:
  workflow_dispatch:  # This enables the manual trigger button in GitHub UI
  
jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner 
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: sweisfeldt/NeoLoadActions
          ref: master  # Specify the master branch
          path: NeoLoadActions
          fetch-depth: 1
      - name: Run NeoLoad Test
        run: |
          "C:\Program Files\NeoLoad 2024.2\bin\NeoLoadCMD.exe" -project "${{ github.workspace }}\NeoLoadActions\NeoLoadActions\SimpleSample.nlp" -noGUI -launch "scenario1" -report "${{ github.workspace }}\NeoLoadActions\NeoLoadActions\SampleReport.html"
        shell: pwsh
