name: Run NeoLoadCMD.exe on Windows

on:
  workflow_dispatch:  # This enables the manual trigger button in GitHub UI
  
jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner 

    steps:
      - name: Run NeoLoad Test
        env:
          NEOLOAD_CMD: C:\Program Files\NeoLoad 2024.2\bin\NeoLoadCMD.exe
          PROJECT_FILE: C:\SimpleSample\SimpleSample.nlp
          REPORT_FILE: C:\SimpleSample\SampleReport.html
        run: |
          "%NEOLOAD_CMD%" -project "%PROJECT_FILE%" -noGUI -launch "scenario1" -report "%REPORT_FILE%"
        shell: cmd
